---
- name: install dependencies
  pkgng: name={{item}} state=present
  with_items:
  - py27-cffi
  - py27-virtualenv

- name: create application user
  user: name={{tahoeuser}} createhome=no

- name: ensure the tahoe data directory exists
  file: path={{tahoedata}} state=directory owner={{tahoeuser}} mode=770

- name: ensure the tahoe build directory exists
  file: path=/usr/local/tahoe-build state=directory owner={{tahoeuser}} mode=770

- name: download the tahoe-package
  get_url: dest=/usr/local/tahoe-build/ url=https://tahoe-lafs.org/source/tahoe-lafs/releases/allmydata-tahoe-1.10.0.zip validate_certs=no

- name: unpack the archive
	command: unzip /usr/local/tahoe-build/allmydata-tahoe-1.10.0.zip

- name: build tahoe (this will take a while...)
	command: python2.7 /usr/local/tahoe-build/allmydata-tahoe-1.10.0/setup.py build

- name: install the binary
	command: mv /usr/local/tahoe-build/allmydata-tahoe-1.10.0/bin/tahoe /usr/local/bin/
