---
- name: install nginx
  pkgng: name=nginx state=present

- name: configure nginx
  template: src=nginx.conf dest=/usr/local/etc/nginx/nginx.conf

- name: ensure the www data directory exists
  file: path={{wwwdata}} state=directory owner={{wwwuser}} mode=770

- name: upload the website
  template: src=index.html dest={{wwwdata}}/index.html owner={{wwwuser}} mode=550

- name: enable nginx at startup time
  lineinfile: dest=/etc/rc.conf state=present line='nginx_enable=YES' create=yes

- name: make sure nginx is running or reloaded
  service: name=nginx state=restarted
